name: Generate apk for QA

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "v*.*.*"
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"

      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.7.2'
          flutter-version: "3.13.9"
          channel: "stable"

      - uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - run: flutter clean
      - run: flutter precache
      - run: flutter pub get

      # https://docs.flutter.dev/deployment/android#build-an-apk
      - name: Build Android APK
        # run: flutter build apk --split-per-abi
        run: flutter build apk

      # - name: Build Android AAB
      #   run: flutter build appbundle

      # TODO sign apk/aab, upload to Google Play

      - name: Push APK to Releases
        uses: actions/upload-artifact@v2
        with:
          name: assets
          # path: |
          #   ${{ github.workspace }}/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          path: |
            ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
